// <auto-generated />
using System;
using AlmaceNando.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlmaceNando.Data.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20260222220753_ResetTotal")]
    partial class ResetTotal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.BarCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("BarCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4bb001ec-24a4-44e4-9894-f9e30003d028"),
                            Code = "7701001",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(2464),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            UpdateAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(2344)
                        },
                        new
                        {
                            Id = new Guid("680af0c3-9d37-49c4-b8f0-3e8c596f4c59"),
                            Code = "7701002",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(3357),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            UpdateAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(3354)
                        });
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Combo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComboProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ComponentProductId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComboProductId");

                    b.HasIndex("ComponentProductId");

                    b.ToTable("Combos");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PriceChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("NN");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("keyword")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Brand = "Colanta",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 230, DateTimeKind.Local).AddTicks(7555),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Leche Colanta 1L",
                            Price = 4200m,
                            SearchName = "leche colanta 1l lacteo nevera",
                            Stock = 20,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "101"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Brand = "Postobon",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8426),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Jugo Hit Mora",
                            Price = 2500m,
                            SearchName = "jugo hit mora bebida nevera",
                            Stock = 15,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "102"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Brand = "Diana",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8449),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Arroz Diana 1kg",
                            Price = 3500m,
                            SearchName = "arroz diana grano",
                            Stock = 50,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "201"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Brand = "Premier",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8452),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Aceite Premier",
                            Price = 12000m,
                            SearchName = "aceite premier cocina",
                            Stock = 10,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "202"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Brand = "Van Camps",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8455),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Atun Van Camps",
                            Price = 6000m,
                            SearchName = "atun van camps conserva",
                            Stock = 30,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "301"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Brand = "Rey",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8458),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Jabon Rey",
                            Price = 2200m,
                            SearchName = "jabon rey aseo",
                            Stock = 40,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "401"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Brand = "Sello Rojo",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8461),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Cafe Sello Rojo",
                            Price = 9000m,
                            SearchName = "cafe sello rojo tinto",
                            Stock = 25,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "501"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Brand = "Doria",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8464),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Pasta Doria",
                            Price = 3000m,
                            SearchName = "pasta doria espagueti",
                            Stock = 35,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "601"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Brand = "Refisal",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8467),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Sal Refisal",
                            Price = 1500m,
                            SearchName = "sal refisal condimento",
                            Stock = 80,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "701"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Brand = "Bimbo",
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 232, DateTimeKind.Local).AddTicks(8470),
                            CurrentPrice = 0m,
                            IsDeleted = false,
                            Name = "Pan Bimbo",
                            Price = 7500m,
                            SearchName = "pan bimbo tajado",
                            Stock = 12,
                            UpdateAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            keyword = "801"
                        });
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.SaleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("productId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("saleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("productId");

                    b.HasIndex("saleId");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("78512d64-2c78-4e70-9c2d-3cc6c96c7829"),
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(135),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            tag = "lacteo"
                        },
                        new
                        {
                            Id = new Guid("cfced2b9-0c7b-4ff2-b61f-7c41952c7451"),
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(1047),
                            IsDeleted = false,
                            ProductId = new Guid("11111111-1111-1111-1111-111111111111"),
                            tag = "nevera"
                        },
                        new
                        {
                            Id = new Guid("d1cb6831-0e92-43fb-9596-a98e5623370d"),
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(1054),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            tag = "bebida"
                        },
                        new
                        {
                            Id = new Guid("a73c3a8c-7c96-44a6-8095-3578f658f3ec"),
                            CreatedAt = new DateTime(2026, 2, 22, 17, 7, 52, 234, DateTimeKind.Local).AddTicks(1056),
                            IsDeleted = false,
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222"),
                            tag = "nevera"
                        });
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.BarCode", b =>
                {
                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Product", "product")
                        .WithMany("BarCodes")
                        .HasForeignKey("ProductId");

                    b.Navigation("product");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Combo", b =>
                {
                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Product", "ComboProduct")
                        .WithMany()
                        .HasForeignKey("ComboProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Product", "ComponentProduct")
                        .WithMany()
                        .HasForeignKey("ComponentProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComboProduct");

                    b.Navigation("ComponentProduct");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.PriceHistory", b =>
                {
                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.SaleDetail", b =>
                {
                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Sale", "sale")
                        .WithMany("SaleDetails")
                        .HasForeignKey("saleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Tag", b =>
                {
                    b.HasOne("AlmaceNando.Domain.Models.Inventory.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Product", b =>
                {
                    b.Navigation("BarCodes");
                });

            modelBuilder.Entity("AlmaceNando.Domain.Models.Inventory.Sale", b =>
                {
                    b.Navigation("SaleDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
